### ISSUE TITLE
bug: Error: Should set security alert url.

### ISSUE THREAD

**Issue by abcfy2** [sett-and-hive/sarif-to-comment-action#94]
### Version

2.0.0

### Current Behavior

![image](https://user-images.githubusercontent.com/5327677/211895332-35c0a238-4e32-4eec-ac73-487ce468b038.png)

### Expected Behavior

Should work.

### Steps to Reproduce

Just like README.md

**Comment by tomwillis608** [comment]
This issue was reproduce while working on #93.
![image](https://user-images.githubusercontent.com/15950648/213954777-a247cfef-5a48-4362-bc60-e95809c5f5d1.png)
This issue is no longer present after #93 was fixed by using `pr-number` instead of `pr_number`.  The `security alert url` error was a side effect of the misnamed parameter name, caused by the erroneous documentation.

**Comment by tomwillis608** [comment]
Resolved in new version v2.0.1 now on the [Marketplace](https://github.com/marketplace/actions/sarif-to-comment-action)
